### PR TITLE
Fix openrazer-meta, add python(3)-pyudev, add python(3)-daemonize

### PR DESCRIPTION
**Pull request by osum4est**

### CODE REVIEW

**Comment by z3ntu** [comment]
My changes on top of yours for now: https://github.com/z3ntu/void-packages/compare/463e567...z3ntu:c32d3e2
The system_groups thing doesn't work for some reason (according to docs it should) and nobody answered me yet in the #xbps irc channel

**Comment by osum4est** [comment]
I had to put `make driver` in do_build() in order for it to build the DKMS modules, otherwise it just put them in src and never built or installed them. Are you building them a different way now?

**Comment by z3ntu** [comment]
`make driver` is just compiling the driver with the current driver sources. The dkms module is supposed to only contain the driver source, which is then built by dkms on the target machines for the currently running kernel.

**Comment by z3ntu** [comment]
And normally the package manager is running a command like `sudo dkms install openrazer-driver/1.0.0` after the package installation so the module is immediately built after installation (and then rebuilt when e.g. the kernel is upgraded).

**Comment by z3ntu** [comment]
Okay the group stuff actually works.

**Comment by z3ntu** [comment]
I guess only the daemon starting mechanism is missing (for `sv up` ?) and then of course packaging of the frontends as imo the driver is pretty useless without them

**Pull request merged**
